### ISSUE TITLE
Hi, can you explain this part?

### ISSUE THREAD

**Issue by Abhinav1217** [YashdalfTheGray/yashdalfthegray.github.io#1]
Hi, 
Can you explain how this part, `(document as IDocumentWithRegistry).` works in Components.ts? You are implementing interface without class. App extends Components which is not implementing the Interface directly? 

Thanks..

**Comment by YashdalfTheGray** [comment]
@Abhinav1217 Oshoot. I didn't see this issue open at all. Um, so this is mostly so that the types flow correctly since I glue on a component registry onto `window.document` and I don't want Typescript being mad at the fact that the component registry doesn't exist on `window.document`. So I created an interface that extends `typeof window.document` and added another property to it.

**Comment by Abhinav1217** [comment]
Thanks, It figures. I was getting anonymous class vibes from that line but couldn't figure out how and why interface got mixed into it.  I ended up with an implementation based on this blog to achieve same thing. https://ultimatecourses.com/blog/classes-vs-interfaces-in-typescript
Thanks for explanation.

**Comment by YashdalfTheGray** [comment]
Yeah, you could use class but I just wanted the typings and not the added structure for the class in that instance.
